### ISSUE TITLE
Prettify large files of markdown side

### ISSUE THREAD

**Issue by hkaur008** [CodeFlow201/GitMarkonics#19]
Larges  files are collected as a paragraphs instead of blocks of texts.
![image](https://user-images.githubusercontent.com/56452820/113477729-94154700-94a1-11eb-9e5b-e60d32bef50d.png)

Result must be represented line wise ! !

**Comment by Rishabhraghwendra18** [comment]
I will like to work on this issue

**Comment by hkaur008** [comment]
> I will like to work on this issue

Good Bug solved !
