### ISSUE TITLE
Design for login functionality

### ISSUE THREAD

**Issue by hkaur008** [CodeFlow201/GitMarkonics#2]
![login-template](https://user-images.githubusercontent.com/56452820/108529209-4336fe00-72fa-11eb-8000-d883c8e43291.png)

Assets : -beautiful-readme-logo.png , background-login.png
Drive of all assets: https://drive.google.com/drive/folders/1MK6JSjbN_HjX9ioDfhjgNch5bwHOEQJx?usp=sharing

**Comment by aniketsingh98571** [comment]
@hkaur008 Do we need to code only frontend?

**Comment by hkaur008** [comment]
> @hkaur008 Do we need to code only frontend?
Its up to you , this issue is for frontend only , Soon backend issue with be opened .

**Comment by aniketsingh98571** [comment]
So what I am going to do:-
1. You have provided the background image, so I will use it in the background.
2.  the middle container is simply a parent container with display flex property and rest of the styling I will do.
3. Align vertical and horizontal center to the container.

**Comment by aniketsingh98571** [comment]
@hkaur008 I would like to work on this issue

**Comment by hkaur008** [comment]
> @hkaur008 I would like to work on this issue



> So what I am going to do:-
> 
> 1. You have provided the background image, so I will use it in the background.
> 2. the middle container is simply a parent container with display flex property and rest of the styling I will do.
> 3. Align vertical and horizontal center to the container.

its in assets drive link given above in issue description.
