### ISSUE TITLE
Add headings from H1 to H6 in a drop drown menu

### ISSUE THREAD

**Issue by hkaur008** [CodeFlow201/GitMarkonics#26]
- [x] h1
# h1
- [x]  h2
## h2

- [x]  h3
### h3

- [x]  h4
#### h4

- [x]  h5
##### h5

Visit #22 for more details

**Comment by yajushiSri** [comment]
Hello, working on this issue. Kindly assign.

**Comment by hkaur008** [comment]
Nyc work !
