### ISSUE TITLE
Design for Register model

### ISSUE THREAD

**Issue by hkaur008** [CodeFlow201/GitMarkonics#3]
![register-template](https://user-images.githubusercontent.com/56452820/108530156-4d0d3100-72fb-11eb-8953-ff3ec0168c00.png)

Assets :- beautiful-readme-logo.png , background-login.png
****Drive of assets**:** https://drive.google.com/drive/folders/1MK6JSjbN_HjX9ioDfhjgNch5bwHOEQJx?usp=sharing

**Comment by Rishabhraghwendra18** [comment]
May I work on this issue ?

**Comment by hkaur008** [comment]
Yeah ! you can start working over this !

**Comment by Rishabhraghwendra18** [comment]
Please assign it to me
