### ISSUE TITLE
No title to Step 1 under "How to Update Your Github Forked Repository" in Readme.md

### ISSUE THREAD

**Issue by Rishabhraghwendra18** [CodeFlow201/GitMarkonics#33]
In Readme.md file , under the section "How to Update Your Github Forked Repository" the step 1 , which is `git remote -v` command,  doesn't have any title like other steps . It looks odd . 

I am thinking to give title to step 1 as _"Lists the remote connections"_

**Comment by chetan6780** [comment]
Any updates for this issue.
If this issue is still open can I contribute in it under LGM-SOC

**Comment by Yashnatani021-coder** [comment]
@chetan6780 it is already assigned you can work on some other issue.
If it is not done then it will be assigned to you
