### ISSUE TITLE
Add Code of Conduct, Project Admin and License in Readme

### ISSUE THREAD

**Issue by Shaishav0507** [CodeFlow201/GitMarkonics#38]
Hey @yajushiSri @Yashnatani021-coder 
I would like to add Code of Conduct, project admin and license in Readme File.
Please assign it to me.
Thanks

**Comment by Shaishav0507** [comment]
@Yashnatani021-coder Can I work on this issue ?

**Comment by Ayan-thecodeking** [comment]
hey @Yashnatani021-coder  please assign this to me ...that will be great if i got any of the task to work in
so please assign me for any one whether it is code of conduct or project admin section 
:)

**Comment by Shaishav0507** [comment]
Done and merged
