### ISSUE TITLE
Logo in readme not visible in dark mode

### ISSUE THREAD

**Issue by supzi-del** [CodeFlow201/GitMarkonics#49]
![Screenshot (224)](https://user-images.githubusercontent.com/78655439/122611590-37d4c300-d09f-11eb-973c-0111445efba7.png)
The text gitmarkonics is not visible in the dark mode of github. I would like to add the logo that is there on the website with a white background to make it visible.
Please assign to me under LGMSOC.

**Comment by varshitha1707** [comment]
I can make the ReadMe logo visible in dark mode as well as light mode, because once the logo is changed from dark to light it wont be visible on the light mode.
Please assign to me under LGMSOC21.

**Comment by supzi-del** [comment]
Hey @Yashnatani021-coder actually I opened the issue to work on it hoping that you would assign it to me.

**Comment by supzi-del** [comment]
@varshitha1707 You could always look for open issues or create your own and get assigned :)

**Comment by varshitha1707** [comment]
> @varshitha1707 You could always look for open issues or create your own and get assigned :)

I apologise for not noticing your request to also be assigned. 
But, I already edited it and created a pull request.
