### ISSUE TITLE
Adding dynamic text to "Register HERE" in register page.

### ISSUE THREAD

**Issue by Surajvatsya** [CodeFlow201/GitMarkonics#54]
**Is your feature request related to a problem? Please describe.**
I would like to enhance the text of the register page to a dynamic one. 

**Describe the solution you'd like**
 I would modify text as a function of time f(t), so that it becomes eye-catching and user friendly.

![Screenshot (3202)](https://user-images.githubusercontent.com/68156079/122795649-27109100-d2db-11eb-9273-a578f2d5fcdd.png)
![Screenshot (3203)](https://user-images.githubusercontent.com/68156079/122795683-3263bc80-d2db-11eb-8beb-b6700dd24927.png)
![Screenshot (3204)](https://user-images.githubusercontent.com/68156079/122795704-37287080-d2db-11eb-8baf-c321f525198e.png)
![Screenshot (3205)](https://user-images.githubusercontent.com/68156079/122795718-3b548e00-d2db-11eb-90cb-9542f238d945.png)
![Screenshot (3206)](https://user-images.githubusercontent.com/68156079/122795744-3f80ab80-d2db-11eb-8da1-b2c481bb2282.png)
![Screenshot (3207)](https://user-images.githubusercontent.com/68156079/122795759-427b9c00-d2db-11eb-9ae2-bb14686959ea.png)

**Comment by Surajvatsya** [comment]
@hkaur008 @Yashnatani021-coder , please ma'am assign it to me.

**Comment by hkaur008** [comment]
> @hkaur008 @Yashnatani021-coder , please ma'am assign it to me.

do you still want to take up this issue ?

**Comment by Surajvatsya** [comment]
yes @hkaur008
