### ISSUE TITLE
Make react icons fit inside input field of registration page.

### ISSUE THREAD

**Issue by Surajvatsya** [CodeFlow201/GitMarkonics#56]
**Is your feature request related to a problem? Please describe.**
Make react icons fit inside the input field of the registration page which was initially odd-looking inside the input box.

**Describe the solution you'd like**
I have changed the icons with more user friendly having less font size compared to the initial one.

@Yashnatani021-coder @hkaur008  please assign this issue to me.
I'm putting down a short snap of my changes, have a look.

![Screenshot (3234)](https://user-images.githubusercontent.com/68156079/123134825-cf0a9380-d46e-11eb-99f9-8eb389f10dab.png)

**Comment by Surajvatsya** [comment]
please compare this icon to the original one. ..

**Comment by hkaur008** [comment]
> please compare this icon to the original one. ..
do you still want to take up this issue?

**Comment by Surajvatsya** [comment]
yes @hkaur008
