### ISSUE TITLE
custom scrollbar

### ISSUE THREAD

**Issue by kumarishalini6** [CodeFlow201/GitMarkonics#57]
please assign me this issue

**Comment by Yashnatani021-coder** [comment]
can u please ellaborate the issue

**Comment by kumarishalini6** [comment]
We have a scroll bar attached with our window to scroll it top bottom , that is of silver colour by default so I want to design it according to the project's theme

**Comment by kumarishalini6** [comment]
> can u please ellaborate the issue

![InkedGit Markonics - Personal - Microsoft​ Edge 6_25_2021 03_16_57 PM_LI](https://user-images.githubusercontent.com/69043944/123406502-7662f580-d557-11eb-80f0-f539174a3cad.jpg)

**Comment by kumarishalini6** [comment]
can i work on this issue ??

**Comment by hkaur008** [comment]
You still want to take up this issue ?

**Comment by kumarishalini6** [comment]
> You still want to take up this issue ?

If you allow me I can

**Comment by kumarishalini6** [comment]
Can you please assign me

**Comment by hkaur008** [comment]
>this issue is alotted to someone else . thanks for showing for taking up this issue
