### ISSUE TITLE
Add Colorful Scrollbar for text editor and output section

### ISSUE THREAD

**Issue by ROHAN842** [CodeFlow201/GitMarkonics#64]
**Describe the solution you'd like**
I would like design scrollbar with linear gradient colors.

Can I work on this issue??

Could you please assign this issue to me under LGMSOC??

**Additional context**
![image](https://user-images.githubusercontent.com/61961107/123951163-1f7b7700-d9c2-11eb-966e-d9a9d043b590.png)

**Comment by ROHAN842** [comment]
@yajushiSri kindly assign this issue to me 🙏🏻🙏🏻🙏🏻🙏🏻

**Comment by hkaur008** [comment]
do you still want to take up this issue?

**Comment by ROHAN842** [comment]
Yes
